import { isLocale, siteContent, type Locale } from "../../site-content";

export default async function ResearchPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: value } = await params;
  const locale: Locale = isLocale(value) ? value : "en";
  const copy = siteContent[locale].research;
  return <main className="bg-stone-50">
    <section className="mx-auto max-w-7xl px-6 pb-20 pt-24"><div className="max-w-3xl"><p className="text-sm font-medium uppercase tracking-[0.25em] text-stone-500">{copy.eyebrow}</p><h1 className="mt-5 text-5xl font-semibold tracking-tight text-stone-900 md:text-6xl">{copy.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-600">{copy.intro}</p></div></section>
    <section className="border-t border-stone-200 bg-white/80"><div className="mx-auto max-w-7xl"><div className="border-b border-stone-200 px-6 py-6 md:px-10"><p className="text-xs font-medium uppercase tracking-[0.2em] text-stone-500">{copy.areas}</p></div><div className="grid grid-cols-1 md:grid-cols-2">{copy.items.map(([title, description, status], index) => <article key={title} className="group border-b border-stone-200 p-8 transition-colors hover:bg-stone-100 md:p-10 md:nth-[odd]:border-r"><div className="flex items-start justify-between gap-6"><p className="text-sm text-stone-500">0{index + 1}</p><span className="rounded-full border border-stone-300 bg-stone-50 px-3 py-1 text-xs text-stone-600">{status}</span></div><h2 className="mt-12 text-2xl font-medium tracking-tight text-stone-900">{title}</h2><p className="mt-4 max-w-lg leading-7 text-stone-600">{description}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-12 md:grid-cols-[1fr_2fr]"><div><p className="text-sm uppercase tracking-[0.2em] text-stone-500">{copy.log}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-stone-900">{copy.logTitle}</h2><p className="mt-6 max-w-sm leading-7 text-stone-500">{copy.logText}</p></div><div className="border-t border-stone-200">{copy.notes.map(([title, category]) => <article key={title} className="grid gap-4 border-b border-stone-200 py-6 md:grid-cols-[100px_1fr_auto] md:items-center md:px-4"><p className="text-sm text-stone-500">2026</p><div><h3 className="text-base font-medium text-stone-900">{title}</h3><p className="mt-1 text-sm text-stone-500">{category}</p></div><span className="text-stone-400">→</span></article>)}</div></div></section>
    <section className="border-t border-stone-200 bg-white/80"><div className="mx-auto max-w-7xl px-6 py-24"><div className="max-w-3xl"><p className="text-sm uppercase tracking-[0.2em] text-stone-500">{copy.method}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-stone-900 md:text-5xl">{copy.methodTitle}</h2><p className="mt-8 text-lg leading-8 text-stone-600">{copy.methodText}</p></div></div></section>
  </main>;
}
