import { isLocale, siteContent, type Locale } from "../../site-content";

export default async function LabPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: value } = await params;
  const locale: Locale = isLocale(value) ? value : "en";
  const copy = siteContent[locale].lab;
  return <main className="bg-stone-50">
    <section className="mx-auto max-w-7xl px-6 pb-20 pt-24"><div className="max-w-3xl"><p className="text-sm font-medium uppercase tracking-[0.25em] text-stone-500">{copy.eyebrow}</p><h1 className="mt-5 text-5xl font-semibold tracking-tight text-stone-900 md:text-6xl">{copy.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-600">{copy.intro}</p></div></section>
    <section className="border-y border-stone-200 bg-white/80"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 border-b border-stone-200 px-6 py-6 sm:flex-row sm:items-center md:px-10"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-stone-500">{copy.status}</p><h2 className="mt-2 text-lg font-medium text-stone-900">{copy.statusTitle}</h2></div><div className="flex items-center gap-3 text-sm text-stone-600"><span className="h-2 w-2 rounded-full bg-emerald-500" />{copy.operational}</div></div><div className="grid grid-cols-2 divide-x divide-stone-200 sm:grid-cols-4">{[[copy.web, "Online"], [copy.network, "Connected"], [copy.services, "04"], [copy.environment, "Local"]].map(([label, value]) => <div key={label} className="border-t border-stone-200 px-6 py-8 first:border-t-0 sm:border-t-0 md:px-10"><p className="text-xs uppercase tracking-[0.15em] text-stone-500">{label}</p><p className="mt-3 text-lg font-medium text-stone-900">{locale === "zh" ? ({ Online: "在线", Connected: "已连接", Local: "本地" }[value] ?? value) : value}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-12 md:grid-cols-2"><div><p className="text-sm uppercase tracking-[0.2em] text-stone-500">{copy.host}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-stone-900">{copy.hostTitle}</h2><p className="mt-6 max-w-lg leading-7 text-stone-600">{copy.hostText}</p></div><div className="border-t border-stone-200">{copy.infra.map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-stone-200 py-5"><span className="text-sm text-stone-500">{label}</span><span className="text-sm text-stone-900">{value}</span></div>)}</div></div></section>
    <section className="border-t border-stone-200 bg-white/80"><div className="mx-auto max-w-7xl"><div className="border-b border-stone-200 px-6 py-6 md:px-10"><p className="text-xs font-medium uppercase tracking-[0.2em] text-stone-500">{copy.services}</p></div><div className="grid grid-cols-1 md:grid-cols-2">{copy.servicesList.map(([name, description, status]) => <article key={name} className="border-b border-stone-200 p-8 transition-colors hover:bg-stone-100 md:p-10 md:nth-[odd]:border-r"><div className="flex items-center justify-between gap-6"><h2 className="text-lg font-medium text-stone-900">{name}</h2><div className="flex items-center gap-2 text-xs text-stone-500"><span className={`h-1.5 w-1.5 rounded-full ${status === (locale === "zh" ? "在线" : "Online") || status === (locale === "zh" ? "已连接" : "Connected") ? "bg-emerald-500" : "bg-stone-400"}`} />{status}</div></div><p className="mt-3 text-sm leading-6 text-stone-600">{description}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24"><div><p className="text-sm uppercase tracking-[0.2em] text-stone-500">{copy.architecture}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-stone-900">{copy.architectureTitle}</h2></div><div className="mt-12 overflow-x-auto"><div className="flex min-w-[700px] items-center gap-4">{[["Internet", "Public Web"], ["Network", "Cloudflare"], ["Tunnel", "Cloudflare Tunnel"], ["Host", "MacBook Pro"]].map(([label, value], index) => <div key={label} className="contents"><div className="flex-1 border border-stone-200 bg-white p-6"><p className="text-xs uppercase tracking-[0.15em] text-stone-500">{label}</p><p className="mt-3 font-medium text-stone-900">{value}</p></div>{index < 3 && <span className="text-stone-400">→</span>}</div>)}</div></div></section>
    <section className="border-t border-stone-200 bg-white/80"><div className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-12 md:grid-cols-[1fr_2fr]"><div><p className="text-sm uppercase tracking-[0.2em] text-stone-500">{copy.experiments}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-stone-900">{copy.experimentsTitle}</h2></div><div className="border-t border-stone-200">{copy.experimentsList.map(([title, description, status], index) => <article key={title} className="grid gap-5 border-b border-stone-200 py-7 md:grid-cols-[60px_1fr_auto]"><p className="text-sm text-stone-500">0{index + 1}</p><div><h3 className="font-medium text-stone-900">{title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-stone-600">{description}</p></div><span className="text-xs text-stone-500">{status}</span></article>)}</div></div></div></section>
  </main>;
}
