import { isLocale, siteContent, type Locale } from "../../site-content";

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: value } = await params;
  const locale: Locale = isLocale(value) ? value : "en";
  const copy = siteContent[locale].about;
  return <main className="bg-stone-50">
    <section className="mx-auto max-w-7xl px-6 pb-24 pt-24"><div className="max-w-4xl"><p className="text-sm font-medium uppercase tracking-[0.25em] text-stone-500">{copy.eyebrow}</p><h1 className="mt-5 text-5xl font-semibold tracking-tight text-stone-900 md:text-6xl">{copy.title}</h1><p className="mt-8 max-w-2xl whitespace-pre-line text-lg leading-8 text-stone-600">{copy.intro}</p></div></section>
    <section className="border-y border-stone-200 bg-white/80"><div className="mx-auto grid max-w-7xl md:grid-cols-2"><div className="border-b border-stone-200 p-8 md:border-b-0 md:border-r md:p-12"><p className="text-xs font-medium uppercase tracking-[0.2em] text-stone-500">{copy.idea}</p><h2 className="mt-5 text-3xl font-semibold tracking-tight text-stone-900">{copy.ideaTitle}</h2></div><div className="p-8 md:p-12"><p className="whitespace-pre-line leading-8 text-stone-600">{copy.ideaText}</p></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-12 md:grid-cols-[1fr_2fr]"><div><p className="text-sm uppercase tracking-[0.2em] text-stone-500">{copy.focus}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-stone-900">{copy.focusTitle}</h2></div><div className="border-t border-stone-200">{copy.focuses.map(([title, description], index) => <article key={title} className="grid gap-5 border-b border-stone-200 py-8 md:grid-cols-[60px_1fr]"><p className="text-sm text-stone-500">0{index + 1}</p><div><h3 className="text-lg font-medium text-stone-900">{title}</h3><p className="mt-3 max-w-xl text-sm leading-7 text-stone-600">{description}</p></div></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 pb-24"><p className="text-sm uppercase tracking-[0.2em] text-stone-500">{copy.principles}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-stone-900">{copy.principleTitle}</h2><div className="mt-12 grid border-t border-stone-200 md:grid-cols-2">{copy.principleItems.map(([title, description], index) => <article key={title} className="border-b border-stone-200 p-8 md:p-10 md:nth-[odd]:border-r"><div className="flex items-start justify-between gap-6"><span className="text-sm text-stone-500">0{index + 1}</span><h3 className="text-xl font-medium text-stone-900">{title}</h3></div><p className="mt-6 max-w-md text-sm leading-7 text-stone-600">{description}</p></article>)}</div></section>
    <section className="border-t border-stone-200 bg-white/80"><div className="mx-auto max-w-7xl px-6 py-24"><div className="max-w-3xl"><p className="text-sm uppercase tracking-[0.2em] text-stone-500">Personal Lab</p><h2 className="mt-4 whitespace-pre-line text-4xl font-semibold tracking-tight text-stone-900 md:text-5xl">{copy.closing}</h2><p className="mt-8 text-lg leading-8 text-stone-600">{copy.closingText}</p></div></div></section>
  </main>;
}
